spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/notifications
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.example.com   # À configurer plus tard avec un vrai serveur SMTP
    port: 587
    username: your-email@example.com
    password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8083