server:
  port: 8080

spring:
  application:
    name: plateforme-universitaire

    autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchClientAutoConfiguration
        - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
        - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration

  datasource:
    url: jdbc:mysql://localhost:3306/plateforme_universitaire?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:}
    password: ${ELASTICSEARCH_PASSWORD:}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
  expiration: 86400000      # 24 heures
  refresh-expiration: 604800000  # 7 jours

# Springdoc / Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha

# Logging
logging:
  level:
    com.universite: DEBUG
    org.springframework.security: INFO



